credentials:
  usernames:
    admin:
      email: admin@gmail.com
      name: Admin
      password: "$2b$12$u0PQ2LpQTPNn6I4xLSC20.jGzjYL/Ne.tqwddvOV5jAW4oYZl/y5y"

cookie:
  name: kittu_cookie
  key: random_key_123
  expiry_days: 30

preauthorized:
  emails:
    - admin@gmail.com
