GOOGLE_CLIENT_ID="691305688044-u6hdlc485tegoop9tjol0s3i7aohp4lr.apps.googleusercontent.com "
GOOGLE_CLIENT_SECRET="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"
REDIRECT_URI="https://chatbot-mrdkszkw3cnp8ymk7fzdhs.streamlit.app/"
